# Generated by Django 5.0.4 on 2024-05-05 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_author_blog_author_id_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 5, 5, 23, 45, 41, 468384), verbose_name='Дата комментария'),
        ),
    ]
